name: Build IPA
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code (manual)
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.ref }}
          
      - name: Build IPA
        run: |
          cd Spawn-Me-2.0
          xcodebuild -workspace SpawnMe.xcworkspace \
            -scheme SpawnMe \
            -configuration Release \
            -archivePath build/SpawnMe.xcarchive \
            archive
          xcodebuild -exportArchive \
            -archivePath build/SpawnMe.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/Release \
            -allowProvisioningUpdates
            
      - name: Store IPA
        run: |
          mkdir -p artifacts
          cp Spawn-Me-2.0/build/Release/SpawnMe.ipa artifacts/
          
      - name: Upload artifact (manual)
        run: |
          echo "IPA built at: Spawn-Me-2.0/build/Release/SpawnMe.ipa"
          echo "Download from Actions artifacts tab"
